import assert from 'assert';
import { ReconciliationEngine } from '../src/trust-kernel/reconciliationEngine.js';
import { runtimeDataToEvidence } from '../src/runtime/runtimeEvidence.js';
import type { Claim, Evidence, RuntimeEventKind, RuntimeOutcome } from '../src/trust-kernel/types.js';

const subject = 'agent:mailer'; const resource = 'mail-class';
function declaration(predicate: 'CAN' | 'CANNOT' = 'CAN'): Claim { return { id: `decl-${predicate}`, subject, predicate, action: 'SEND', resource, source: 'DECLARATION', status: 'DECLARED', provenance: [{ sourceType: 'DECLARATION', artifact: 'taidyup.json' }] }; }
function observed(sourceType: 'STATIC' | 'CONNECTED' = 'STATIC', observation?: 'PRESENCE' | 'ABSENCE_OBSERVED', time = '2026-09-06T10:00:00.000Z'): Evidence { return { id: `${sourceType}-${observation || 'presence'}-${time}`, type: `${sourceType}_CAPABILITY`, sourceType, subject, observedAt: time, collectorId: 'test', collectorVersion: '1', artifact: 'fixture.json', data: { capability: 'SEND', resource, ...(observation ? { observation } : {}), ...(sourceType === 'CONNECTED' ? { connectedSnapshot: { mode: 'POINT_IN_TIME', sourceInstance: 'local', scope: 'workflow', completeness: 'COMPLETE', retrievalStatus: 'SUCCESS', observedAt: time } } : {}) }, strength: 'AGENT_BOUND', sha256: 'fixture', provenance: { file: 'fixture.json' } }; }
function runtime(kind: RuntimeEventKind, run: string, time: string, outcome?: RuntimeOutcome, bound = true): Evidence { return runtimeDataToEvidence({ schemaVersion: '0.1', eventKind: kind, eventTime: time, operation: { action: 'SEND', resource }, bindings: { subject: bound ? { state: 'BOUND', method: 'STRUCTURAL', value: subject, evidence: 'analysis binding', evidenceRef: 'evidence:subject-binding' } : { state: 'UNBOUND', value: subject }, action: { state: 'BOUND', method: 'STRUCTURAL', value: 'SEND', evidence: 'wrapper dispatch', evidenceRef: 'evidence:dispatch' }, resource: { state: 'BOUND', method: 'STRUCTURAL', value: resource, evidence: 'registered class', evidenceRef: 'evidence:resource' }, constraints: { state: 'UNBOUND' } }, source: { kind: 'IMPORTED_ARTIFACT', identity: 'runtime.fixture' }, sourceEventId: `${run}:${kind}`, observationScope: { kind: 'RUN', id: run }, completeness: 'PARTIAL_OBSERVATION', sanitization: { policy: 'ALLOWLIST_V0', rawPayloadPersisted: false, droppedFields: ['arguments', 'result', 'exception'] }, outcome, runId: run }, 'runtime.jsonl', 1); }

const success = ReconciliationEngine.reconcile([declaration()], [observed(), runtime('EXECUTION_STARTED', 'a', '2026-09-06T10:01:00.000Z'), runtime('EXECUTION_COMPLETED', 'a', '2026-09-06T10:02:00.000Z', 'SUCCEEDED')]);
assert.equal(success.reconciledClaims[0].status, 'SUPPORTED'); assert.equal(success.reconciledClaims[0].runtimeAssessment?.observationState, 'COMPLETION_OBSERVED'); assert.equal(success.reconciledClaims[0].runtimeAssessment?.latestOutcome, 'SUCCEEDED');
const none = ReconciliationEngine.reconcile([declaration()], [observed()]); assert.equal(none.reconciledClaims[0].runtimeAssessment?.observationState, 'NO_OBSERVATION');
const failure = ReconciliationEngine.reconcile([declaration()], [observed(), runtime('INVOCATION_ATTEMPTED', 'b', '2026-09-06T10:00:00.000Z'), runtime('EXECUTION_STARTED', 'b', '2026-09-06T10:01:00.000Z'), runtime('EXECUTION_COMPLETED', 'b', '2026-09-06T10:02:00.000Z', 'FAILED')]); assert.equal(failure.reconciledClaims[0].status, 'SUPPORTED'); assert.equal(failure.reconciledClaims[0].runtimeAssessment?.latestOutcome, 'FAILED');
const undeclared = ReconciliationEngine.reconcile([], [runtime('EXECUTION_COMPLETED', 'c', '2026-09-06T10:02:00.000Z', 'SUCCEEDED')]); assert.equal(undeclared.reconciledClaims[0].status, 'UNDECLARED_OBSERVATION');
const attemptedCannot = ReconciliationEngine.reconcile([declaration('CANNOT')], [runtime('INVOCATION_ATTEMPTED', 'd', '2026-09-06T10:00:00.000Z')]); assert.notEqual(attemptedCannot.reconciledClaims[0].status, 'CONFLICT');
const completedCannot = ReconciliationEngine.reconcile([declaration('CANNOT')], [runtime('EXECUTION_COMPLETED', 'd', '2026-09-06T10:02:00.000Z', 'SUCCEEDED')]); assert.equal(completedCannot.reconciledClaims[0].status, 'CONFLICT'); assert.doesNotMatch(completedCannot.findings[0].description, /unauthori[sz]ed|illegal|unsafe|non-compliant/i);
const unbound = ReconciliationEngine.reconcile([], [runtime('EXECUTION_COMPLETED', 'e', '2026-09-06T10:02:00.000Z', 'SUCCEEDED', false)]); assert.equal(unbound.reconciledClaims.length, 0); assert.equal(unbound.unboundRuntimeObservations?.length, 1);
const drift = ReconciliationEngine.reconcile([declaration()], [observed(), observed('CONNECTED', 'PRESENCE', '2026-09-06T10:00:00.000Z'), runtime('EXECUTION_COMPLETED', 'f', '2026-09-06T10:01:00.000Z', 'SUCCEEDED'), observed('CONNECTED', 'ABSENCE_OBSERVED', '2026-09-06T10:02:00.000Z')]); assert.equal(drift.reconciledClaims[0].runtimeAssessment?.observationState, 'COMPLETION_OBSERVED'); assert.equal(drift.reconciledClaims[0].runtimeAssessment?.lastObservedAt, '2026-09-06T10:01:00.000Z');
const incomplete = ReconciliationEngine.reconcile([declaration()], [observed(), runtime('EXECUTION_COMPLETED', 'g', '2026-09-06T10:02:00.000Z', 'UNKNOWN')]); assert(incomplete.reconciledClaims[0].runtimeAssessment?.diagnostics.includes('RUNTIME_START_MISSING'));
console.log('Runtime reconciliation V0: A-G PASS');
