import { ReconciledTrustState } from './types.js';

export class ReportGenerator {
  /**
   * Generates a clean human-readable Markdown developer validation report.
   */
  public static generateMarkdownReport(projectName: string, state: ReconciledTrustState): string {
    const lines: string[] = [];

    lines.push(`# TAIDYUP TECHNICAL PASSPORT & VALIDATION REPORT`);
    lines.push(`**Project:** \`${projectName}\`  `);
    lines.push(`**Timestamp:** \`${state.timestamp}\`  `);
    lines.push(`**Trust Kernel Engine Version:** \`${state.schemaVersion}\`  \n`);

    lines.push(`## SUMMARY METRICS`);
    lines.push(`* **Total Claims Evaluated:** ${state.summary.totalClaims}`);
    lines.push(`* **Supported Implementation Claims:** ${state.summary.supportedCount}`);
    lines.push(`* **Unverified Claims:** ${state.summary.unverifiedCount}`);
    lines.push(`* **Declaration Conflicts:** ${state.summary.conflictCount}`);
    lines.push(`* **Undeclared Observations:** ${state.summary.undeclaredCount}`);
    lines.push(`* **Unknown / Ambiguous States:** ${state.summary.unknownCount}`);
    lines.push(`* **Critical Governance Findings:** ${state.summary.criticalFindingsCount}\n`);

    lines.push(`---`);
    lines.push(`## RECONCILED CLAIMS DETAIL\n`);

    for (const claim of state.reconciledClaims) {
      const icon = claim.status === 'SUPPORTED' ? '✅' :
                   claim.status === 'UNVERIFIED' ? '⚠️' :
                   claim.status === 'CONFLICT' ? '🚨' :
                   claim.status === 'UNDECLARED_OBSERVATION' ? '🔍' : '❓';

      lines.push(`### ${icon} \`${claim.subject}\` — ${claim.predicate} ${claim.action || ''} ${claim.resource || ''}`);
      lines.push(`* **Status:** \`${claim.status}\``);
      lines.push(`* **Source:** \`${claim.source}\``);
      lines.push(`* **Confidence:** \`${claim.confidence ? Math.round(claim.confidence * 100) + '%' : 'N/A'}\``);
      if (claim.provenance && claim.provenance.length > 0) {
        lines.push(`* **Provenance:** ${claim.provenance.map(p => `\`${p.artifact}${p.location ? ':' + p.location : ''}\``).join(', ')}`);
      }
      lines.push(``);
    }

    lines.push(`---`);
    lines.push(`## TECHNICAL FINDINGS & CONFLICTS\n`);

    if (state.findings.length === 0) {
      lines.push(`*No critical governance conflicts or undeclared capabilities detected.*`);
    } else {
      for (const finding of state.findings) {
        const sevIcon = finding.severity === 'CRITICAL' ? '💥' : finding.severity === 'HIGH' ? '🚨' : '⚠️';
        lines.push(`### ${sevIcon} [${finding.severity}] ${finding.title}`);
        lines.push(`* **Type:** \`${finding.type}\``);
        lines.push(`* **Description:** ${finding.description}`);
        if (finding.declaredText) lines.push(`* **Declared:** \`${finding.declaredText}\``);
        if (finding.observedText) lines.push(`* **Observed:** \`${finding.observedText}\``);
        lines.push(`* **File Location:** \`${finding.provenance.file}\``);
        lines.push(``);
      }
    }

    lines.push(`---`);
    lines.push(`*Report generated by tAIdyup Engine.*`);

    return lines.join('\n');
  }
}
